famous_people = [

    {'name': 'Cristiano Ronaldo', 'follower count': 575, 'description': 'footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower count': 470, 'description': 'footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower count': 430, 'description': 'singer and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower count': 400, 'description': 'model and businesswoman', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower count': 395, 'description': 'actor and former wrestler', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower count': 365, 'description': 'TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower count': 360, 'description': 'singer and actress', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower count': 290, 'description': 'singer and actress', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower count': 320, 'description': 'singer and songwriter', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower count': 305, 'description': 'singer', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower count': 290, 'description': 'model', 'country': 'United States'},
    {'name': 'Neymar', 'follower count': 215, 'description': 'footballer', 'country': 'Brazil'},
    {'name': 'Virat Kohli', 'follower count': 255, 'description': 'cricketer', 'country': 'India'},
    {'name': 'Zendaya', 'follower count': 190, 'description': 'actress and singer', 'country': 'United States'},
    {'name': 'Shakira', 'follower count': 125, 'description': 'singer', 'country': 'Colombia'},
    {'name': 'Jennifer Lopez', 'follower count': 220, 'description': 'singer and actress', 'country': 'United States'},
    {'name': 'LeBron James', 'follower count': 150, 'description': 'basketball player', 'country': 'United States'},
    {'name': 'Kanye West', 'follower count': 140, 'description': 'rapper and producer', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower count': 125, 'description': 'TV host and comedian', 'country': 'United States'},
    {'name': 'David Beckham', 'follower count': 100, 'description': 'former footballer', 'country': 'United Kingdom'},
    {'name': 'Billie Eilish', 'follower count': 115, 'description': 'singer', 'country': 'United States'},
    {'name': 'Drake', 'follower count': 120, 'description': 'rapper and producer', 'country': 'Canada'},
    {'name': 'Cardi B', 'follower count': 105, 'description': 'rapper', 'country': 'United States'},
    {'name': 'Dua Lipa', 'follower count': 95, 'description': 'singer', 'country': 'United Kingdom'},
    {'name': 'Kourtney Kardashian', 'follower count': 120, 'description': 'TV personality', 'country': 'United States'},
    {'name': 'Will Smith', 'follower count': 130, 'description': 'actor', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower count': 105, 'description': 'singer and actress', 'country': 'United States'},
    {'name': 'Rihanna', 'follower count': 120, 'description': 'singer and businesswoman', 'country': 'Barbados'},
    {'name': 'Priyanka Chopra', 'follower count': 90, 'description': 'actress and producer', 'country': 'India'},
    {'name': 'Emma Watson', 'follower count': 60, 'description': 'actress', 'country': 'United Kingdom'},
    {'name': 'Chris Hemsworth', 'follower count': 55, 'description': 'actor', 'country': 'Australia'},
    {'name': 'Gal Gadot', 'follower count': 80, 'description': 'actress', 'country': 'Israel'},
    {'name': 'Tom Holland', 'follower count': 60, 'description': 'actor', 'country': 'United Kingdom'},
    {'name': 'Ed Sheeran', 'follower count': 85, 'description': 'singer-songwriter', 'country': 'United Kingdom'},
    {'name': 'Harry Styles', 'follower count': 70, 'description': 'singer and actor', 'country': 'United Kingdom'},
    {'name': 'Snoop Dogg', 'follower count': 75, 'description': 'rapper', 'country': 'United States'},
    {'name': 'Shawn Mendes', 'follower count': 65, 'description': 'singer', 'country': 'Canada'},
    {'name': 'Bruno Mars', 'follower count': 55, 'description': 'singer', 'country': 'United States'},
    {'name': 'Gigi Hadid', 'follower count': 80, 'description': 'model', 'country': 'United States'},
    {'name': 'Lady Gaga', 'follower count': 90, 'description': 'singer and actress', 'country': 'United States'},
    {'name': 'Robert Downey Jr.', 'follower count': 50, 'description': 'actor', 'country': 'United States'},
    {'name': 'Vin Diesel', 'follower count': 75, 'description': 'actor', 'country': 'United States'},
    {'name': 'Camila Cabello', 'follower count': 55, 'description': 'singer', 'country': 'United States'},
    {'name': 'Jason Momoa', 'follower count': 50, 'description': 'actor', 'country': 'United States'},
    {'name': 'Hugh Jackman', 'follower count': 45, 'description': 'actor', 'country': 'Australia'},
    {'name': 'Millie Bobby Brown', 'follower count': 60, 'description': 'actress', 'country': 'United Kingdom'},
    {'name': 'Zendaya', 'follower count': 60, 'description': 'actress and singer', 'country': 'United States'},

]